server:
  port: 8085

logging:
  level:
    root: info
    com.gn: debug

logstash:
  host: localhost
  enableInnerLog: false

spring:
  application:
    name: test1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.126.129:8848
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: 192.168.126.129:9092
    # 生产者
    producer:
      # 重试次数，设置大于0的值，则客户端会将发送失败的记录重新发送
      retries: 3
      batch-size: 16384 #批量处理大小，16K
      buffer-memory: 33554432 #缓冲存储大，32M
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

dubbo:
  application:
    name: test1
  scan:
    # dubbo 服务扫描包
    base-packages: com.gn.test1.api
  protocol:
    # 设置协议为dubbo
    name: dubbo
    # dubbo 协议端口 （-1 表示自增端口，从20880开始）
    port: -1
  registry:
    # 以下是配置中已包含nacos配置的写法
    address: nacos://192.168.126.129:8848
    parameters.register-consumer-url: false
#  cloud:
#    subscribed-services: test1,test2


xxl:
  job:
    ### xxl-job, access token
    accessToken: gn.com
    admin:
      ### 调度中心部署根地址：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://192.168.126.129:8888/xxl-job-admin
    executor:
      address: ''
      appname: test1
      ip: ''
      port: -1
      logpath: /data/applogs/xxl-job/jobhandler
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 3